"""empty message

<<<<<<<< HEAD:migrations/versions/141246b09fd0_.py
Revision ID: 141246b09fd0
Revises: 
Create Date: 2024-02-19 23:43:31.709734
========
<<<<<<<< HEAD:migrations/versions/96da0e81fa4c_.py
Revision ID: 96da0e81fa4c
Revises: 
Create Date: 2024-02-19 17:51:56.679389
========
Revision ID: 2c2bcade1fa4
Revises: 
Create Date: 2024-02-19 13:08:11.383882
>>>>>>>> 99976d755278bb1a677857516aa449ee8219b150:migrations/versions/2c2bcade1fa4_.py
>>>>>>>> cfe0f39f1a42157891975ee93c63dbcc27fc151e:migrations/versions/96da0e81fa4c_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/141246b09fd0_.py
revision = '141246b09fd0'
========
<<<<<<<< HEAD:migrations/versions/96da0e81fa4c_.py
revision = '96da0e81fa4c'
========
revision = '2c2bcade1fa4'
>>>>>>>> 99976d755278bb1a677857516aa449ee8219b150:migrations/versions/2c2bcade1fa4_.py
>>>>>>>> cfe0f39f1a42157891975ee93c63dbcc27fc151e:migrations/versions/96da0e81fa4c_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('identification', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('comment', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identification')
    )
    op.create_table('professional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('identification', sa.String(length=30), nullable=False),
    sa.Column('profession', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('comment', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identification')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status')
    )
    op.create_table('typeservice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_service', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_service')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=False),
    sa.Column('date_init', sa.DateTime(), nullable=True),
    sa.Column('typeservice_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('initial_note', sa.String(length=400), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('close_date', sa.DateTime(), nullable=True),
    sa.Column('close_description', sa.String(length=400), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('delivered_date', sa.DateTime(), nullable=True),
    sa.Column('delivered_description', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professional.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['typeservice_id'], ['typeservice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case')
    op.drop_table('user')
    op.drop_table('typeservice')
    op.drop_table('status')
    op.drop_table('professional')
    op.drop_table('customer')
    op.drop_table('category')
    # ### end Alembic commands ###
